name: Mark Sands
description: Programming Tidbits
url: http://marksands.github.io

pygments: true
markdown: redcarpet

author:
  name: Mark Sands
  email: marksands07@gmail.com
  github: marksands
  twitter: marksands
